FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY frontend/index.html /usr/share/nginx/html/index.html
COPY frontend/script.js /usr/share/nginx/html/script.js
COPY frontend/styles.css /usr/share/nginx/html/styles.css

EXPOSE 8080
